name: Deploy static to GitHub Pages

on:
  push:
    branches:
      - master # 或 main，根据你的默认分支修改
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare publish directory
        run: |
          mkdir -p public/beautiful-html-demo
          cp -r static/* public/beautiful-html-demo/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public